import React, { useState, useEffect, useRef } from 'react';
import { 
  Trophy, Play, RotateCcw, AlertTriangle, Gamepad2, Zap, Brain, 
  LayoutGrid, Sparkles, Search, Disc, ChevronsRight, Target, 
  Binary, Volume2, GitCommit, Eye, Calculator, RefreshCw, 
  Type, Hash, Timer, MousePointer, Layout, Wind, ArrowLeft 
} from 'lucide-react';

// ============================================================================
// 20 FOCUS & MIND CONCENTRATION GAMES LIST CONFIGURATION
// ============================================================================
const GAMES_LIST = [
  { id: 'schulte', title: 'Schulte Grid', category: 'Visual Attention', difficulty: 'Medium', desc: 'Find numbers 1 to 16 in ascending order. Expands peripheral vision.', icon: <LayoutGrid size={16} /> },
  { id: 'letter_scan', title: 'Letter Scan', category: 'Visual Attention', difficulty: 'Easy', desc: 'Scan a grid of distraction letters and locate the target character rapidly.', icon: <Search size={16} /> },
  { id: 'number_bubbles', title: 'Number Bubbles', category: 'Visual Attention', difficulty: 'Medium', desc: 'Tap floating number circles in strict ascending order before they shift.', icon: <Disc size={16} /> },
  { id: 'shifting_arrows', title: 'Shifting Arrows', category: 'Visual Attention', difficulty: 'Hard', desc: 'Match dynamically shifting target directions with random arrows.', icon: <ChevronsRight size={16} /> },
  { id: 'target_tracking', title: 'Target Clicker', category: 'Visual Attention', difficulty: 'Medium', desc: 'Track and click a small target that shifts positions faster with each level.', icon: <Target size={16} /> },
  
  { id: 'simon', title: 'Attention Recall', category: 'Working Memory', difficulty: 'Hard', desc: 'Memorize and replicate a growing sequence of color flashes and audio tones.', icon: <Brain size={16} /> },
  { id: 'matrix', title: 'Matrix Memory', category: 'Working Memory', difficulty: 'Hard', desc: 'Recall the spatial configuration of highlighted tiles on a grid.', icon: <Gamepad2 size={16} /> },
  { id: 'digit_span', title: 'Digit Span', category: 'Working Memory', difficulty: 'Medium', desc: 'Memorize a sequence of digits shown briefly, then type and input them.', icon: <Binary size={16} /> },
  { id: 'tone_memory', title: 'Tone Recall', category: 'Working Memory', difficulty: 'Hard', desc: 'Match a sequence of musical pitches generated by Web Audio synth.', icon: <Volume2 size={16} /> },
  { id: 'path_tracer', title: 'Pattern Tracer', category: 'Working Memory', difficulty: 'Hard', desc: 'Trace a complex path through grid nodes in the sequence shown.', icon: <GitCommit size={16} /> },

  { id: 'stroop', title: 'Stroop Test', category: 'Cognitive Control', difficulty: 'Extreme', desc: 'Name the ink color of the word, not what the word reads. High concentration.', icon: <Eye size={16} /> },
  { id: 'quick_math', title: 'Math Marathon', category: 'Cognitive Control', difficulty: 'Hard', desc: 'Solve rapid math equations under a strict, ticking 2.5s time limit.', icon: <Calculator size={16} /> },
  { id: 'color_switch', title: 'Color Matcher', category: 'Cognitive Control', difficulty: 'Medium', desc: 'Determine if the current color box matches the previous color shown.', icon: <RefreshCw size={16} /> },
  { id: 'anagram_solver', title: 'Anagram Focus', category: 'Cognitive Control', difficulty: 'Medium', desc: 'Unscramble study and focus related words under time pressure.', icon: <Type size={16} /> },
  { id: 'missing_number', title: 'Missing Term', category: 'Cognitive Control', difficulty: 'Medium', desc: 'Identify the missing numeric term from pattern sequences.', icon: <Hash size={16} /> },

  { id: 'reaction', title: 'Alertness Check', category: 'Alertness & Speed', difficulty: 'Easy', desc: 'Click the alert box as soon as the screen background turns green.', icon: <Zap size={16} /> },
  { id: 'time_precision', title: 'Time Precision', category: 'Alertness & Speed', difficulty: 'Extreme', desc: 'Stop a running stopwatch exactly at 1.000 seconds. Tests precision.', icon: <Timer size={16} /> },
  { id: 'click_rush', title: 'Click Rush', category: 'Alertness & Speed', difficulty: 'Medium', desc: 'Tap as many randomly appearing targets as possible in 10 seconds.', icon: <MousePointer size={16} /> },
  { id: 'dual_nback', title: 'Visual N-Back', category: 'Alertness & Speed', difficulty: 'Extreme', desc: 'Recall if current grid position matches the position shown 1 step ago.', icon: <Layout size={16} /> },
  { id: 'zen_breathing', title: 'Zen Breathing', category: 'Alertness & Speed', difficulty: 'Easy', desc: 'Follow guided deep-breathing patterns to lower stress and build calm focus.', icon: <Wind size={16} /> }
];

const CATEGORIES = ['All', 'Visual Attention', 'Working Memory', 'Cognitive Control', 'Alertness & Speed'];

export default function FocusGames() {
  const [activeTab, setActiveTab] = useState('All');
  const [activeGame, setActiveGame] = useState(null);

  const filteredGames = GAMES_LIST.filter(g => activeTab === 'All' || g.category === activeTab);

  if (activeGame) {
    const game = GAMES_LIST.find(g => g.id === activeGame);
    return (
      <div className="space-y-6 animate-fade-in pb-12 animate-fade-in">
        <button
          onClick={() => setActiveGame(null)}
          className="flex items-center gap-2 px-4 py-2 text-xs font-black uppercase text-teal-400 bg-slate-900 border border-slate-800 rounded-xl hover:bg-slate-855 hover:text-teal-300 transition-all cursor-pointer shadow-md"
        >
          <ArrowLeft size={14} />
          Exit to Game Suite
        </button>
        
        <div className="border-b border-slate-800/80 pb-4 mb-4 select-none animate-fade-in">
          <div className="flex items-center gap-2 text-teal-450 font-mono text-[10px] uppercase tracking-widest">
            {game.category} <span className="text-slate-700">|</span> Difficulty: {game.difficulty}
          </div>
          <h2 className="text-2xl font-black text-slate-100 mt-1 uppercase tracking-wide">{game.title}</h2>
        </div>

        <div className="transition-all duration-350">
          {activeGame === 'schulte' && <SchulteGridGame />}
          {activeGame === 'letter_scan' && <LetterScanGame />}
          {activeGame === 'number_bubbles' && <NumberBubblesGame />}
          {activeGame === 'shifting_arrows' && <ShiftingArrowsGame />}
          {activeGame === 'target_tracking' && <TargetTrackingGame />}
          
          {activeGame === 'simon' && <SimonSaysGame />}
          {activeGame === 'matrix' && <MatrixMemoryGame />}
          {activeGame === 'digit_span' && <DigitSpanGame />}
          {activeGame === 'tone_memory' && <ToneMemoryGame />}
          {activeGame === 'path_tracer' && <PathTracerGame />}

          {activeGame === 'stroop' && <StroopGame />}
          {activeGame === 'quick_math' && <QuickMathGame />}
          {activeGame === 'color_switch' && <ColorSwitchGame />}
          {activeGame === 'anagram_solver' && <AnagramSolverGame />}
          {activeGame === 'missing_number' && <MissingNumberGame />}

          {activeGame === 'reaction' && <ReactionTimerGame />}
          {activeGame === 'time_precision' && <TimePrecisionGame />}
          {activeGame === 'click_rush' && <ClickRushGame />}
          {activeGame === 'dual_nback' && <DualNBackGame />}
          {activeGame === 'zen_breathing' && <ZenBreathingGame />}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in pb-12 font-sans select-none">
      {/* Category selector */}
      <div className="flex flex-wrap gap-2.5 pb-3 border-b border-slate-800/80">
        {CATEGORIES.map(cat => (
          <button
            key={cat}
            onClick={() => setActiveTab(cat)}
            className={`px-4.5 py-2.5 rounded-xl font-bold text-xs cursor-pointer transition-all duration-205 uppercase tracking-wide ${
              activeTab === cat
                ? 'bg-gradient-to-r from-teal-500 to-teal-650 text-white shadow-lg shadow-teal-500/15'
                : 'bg-slate-900/60 text-slate-400 border border-slate-850 hover:bg-slate-850 hover:text-slate-200'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Grid of 20 Games */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredGames.map(game => (
          <div 
            key={game.id}
            className="glass-card p-5 rounded-[1.75rem] border border-slate-850 bg-slate-900/40 hover:border-teal-500/20 hover:scale-[1.01] transition-all duration-250 flex flex-col justify-between animate-fade-in"
          >
            <div>
              <div className="flex items-center justify-between mb-3.5">
                <span className={`text-[9px] font-black uppercase px-2 py-0.5 rounded-full border ${
                  game.difficulty === 'Easy' ? 'bg-emerald-950/40 border-emerald-500/25 text-emerald-450' :
                  game.difficulty === 'Medium' ? 'bg-teal-950/40 border-teal-500/25 text-teal-400' :
                  game.difficulty === 'Hard' ? 'bg-amber-950/40 border-amber-500/25 text-amber-400' :
                  'bg-rose-955/40 border-rose-500/25 text-rose-455'
                }`}>
                  {game.difficulty}
                </span>
                <span className="text-[9px] font-black text-slate-500 uppercase tracking-widest">{game.category}</span>
              </div>

              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-slate-950 text-teal-450 border border-slate-800 flex items-center justify-center">
                  {game.icon}
                </div>
                <h3 className="font-extrabold text-slate-100 uppercase tracking-wide text-sm">{game.title}</h3>
              </div>
              <p className="text-slate-400 text-xs mt-3 leading-relaxed font-semibold">{game.desc}</p>
            </div>

            <button
              onClick={() => setActiveGame(game.id)}
              className="mt-5 w-full py-2.5 bg-slate-950 hover:bg-teal-650/15 border border-slate-850 hover:border-teal-500/35 text-teal-450 hover:text-white rounded-xl text-xs font-black uppercase tracking-widest transition-all cursor-pointer flex items-center justify-center gap-1.5"
            >
              <Play size={12} fill="currentColor" /> Play Game
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

// ============================================================================
// WEB AUDIO API Note Generator (Frequency sound pitches)
// ============================================================================
const playSynthTone = (freq) => {
  try {
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;
    const ctx = new AC();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.connect(gain);
    gain.connect(ctx.destination);
    osc.frequency.value = freq;
    osc.start();
    gain.gain.setValueAtTime(0.3, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.45);
    osc.stop(ctx.currentTime + 0.5);
  } catch (e) {}
};

// ============================================================================
// GAME 1: SCHULTE GRID
// ============================================================================
function SchulteGridGame() {
  const [grid, setGrid] = useState([]);
  const [nextNum, setNextNum] = useState(1);
  const [isPlaying, setIsPlaying] = useState(false);
  const [time, setTime] = useState(0);
  const [bestTime, setBestTime] = useState(() => parseFloat(localStorage.getItem('g_schulte_best') || '99.9'));
  const [isWon, setIsWon] = useState(false);
  const timerRef = useRef(null);

  const initGame = () => {
    const arr = Array.from({ length: 16 }, (_, i) => i + 1).sort(() => Math.random() - 0.5);
    setGrid(arr);
    setNextNum(1);
    setTime(0);
    setIsWon(false);
  };

  const startGame = () => {
    initGame();
    setIsPlaying(true);
    if (timerRef.current) clearInterval(timerRef.current);
    const start = Date.now();
    timerRef.current = setInterval(() => {
      setTime(parseFloat(((Date.now() - start) / 1000).toFixed(2)));
    }, 10);
  };

  const handleTile = (num) => {
    if (!isPlaying) return;
    if (num === nextNum) {
      if (num === 16) {
        clearInterval(timerRef.current);
        setIsPlaying(false);
        setIsWon(true);
        if (time < bestTime) {
          setBestTime(time);
          localStorage.setItem('g_schulte_best', String(time));
        }
      } else {
        setNextNum(num + 1);
      }
    }
  };

  useEffect(() => { initGame(); return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-350">
        <div>TIME: <span className="text-teal-400 text-lg font-black">{time.toFixed(2)}s</span></div>
        <div>BEST: <span className="text-slate-200 text-sm">{bestTime === 99.9 ? 'N/A' : `${bestTime}s`}</span></div>
        <div>TARGET: <span className="text-teal-455 text-lg font-black">{isWon ? '✔' : nextNum}</span></div>
      </div>
      <div className="grid grid-cols-4 gap-2.5 w-full aspect-square">
        {grid.map(n => (
          <button
            key={n}
            disabled={!isPlaying}
            onClick={() => handleTile(n)}
            className={`rounded-xl text-lg font-mono font-black border transition-all cursor-pointer ${
              n < nextNum ? 'bg-teal-950/10 border-teal-500/10 text-teal-500/20' :
              isPlaying && n === nextNum ? 'bg-teal-950/20 border-teal-400 text-teal-400 scale-95 shadow-md shadow-teal-500/10' :
              isPlaying ? 'bg-slate-955 border-slate-800 text-slate-200 hover:bg-slate-850' : 'bg-slate-955 border-slate-900 text-slate-600'
            }`}
          >
            {n}
          </button>
        ))}
      </div>
      <button onClick={startGame} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 hover:from-teal-450 hover:to-teal-600 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer shadow-md">
        {isWon ? 'Play Again' : 'Start Focus Run'}
      </button>
    </div>
  );
}

// ============================================================================
// GAME 2: LETTER SCAN
// ============================================================================
function LetterScanGame() {
  const [grid, setGrid] = useState([]);
  const [isPlaying, setIsPlaying] = useState(false);
  const [level, setLevel] = useState(1);
  const [time, setTime] = useState(0);
  const timerRef = useRef(null);

  const startLevel = (lvl) => {
    const totalCount = 64; 
    const targetPos = Math.floor(Math.random() * totalCount);
    const arr = Array(totalCount).fill('Q');
    arr[targetPos] = 'O';
    setGrid(arr);
    setIsPlaying(true);
    if (timerRef.current) clearInterval(timerRef.current);
    const start = Date.now();
    timerRef.current = setInterval(() => {
      setTime(parseFloat(((Date.now() - start) / 1000).toFixed(2)));
    }, 10);
  };

  const handleTile = (char) => {
    if (!isPlaying) return;
    if (char === 'O') {
      clearInterval(timerRef.current);
      setIsPlaying(false);
      if (level < 5) {
        setLevel(level + 1);
        setTimeout(() => startLevel(level + 1), 600);
      } else {
        alert(`Clear! Speed Focus Scan Complete: ${time}s`);
        setLevel(1);
      }
    }
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-5">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-350">
        <div>STAGE: <span className="text-teal-400 text-sm font-black">{level}/5</span></div>
        <div>SCAN TIMER: <span className="text-teal-400 font-black">{time.toFixed(2)}s</span></div>
        <div>FIND: <span className="text-teal-455 font-black">"O"</span></div>
      </div>
      <div className="grid grid-cols-8 gap-1.5 w-full aspect-square bg-slate-950 p-2 rounded-2xl border border-slate-900">
        {grid.map((char, i) => (
          <button
            key={i}
            disabled={!isPlaying}
            onClick={() => handleTile(char)}
            className="text-xs font-mono font-black text-slate-450 hover:bg-slate-900 rounded-lg cursor-pointer transition-all hover:text-teal-455"
          >
            {char}
          </button>
        ))}
      </div>
      {!isPlaying && (
        <button onClick={() => startLevel(1)} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Start Scan
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 3: NUMBER BUBBLES
// ============================================================================
function NumberBubblesGame() {
  const [bubbles, setBubbles] = useState([]);
  const [nextNum, setNextNum] = useState(1);
  const [isPlaying, setIsPlaying] = useState(false);
  const [score, setScore] = useState(0);

  const initBubbles = () => {
    const list = Array.from({ length: 6 }, (_, i) => i + 1).sort(() => Math.random() - 0.5);
    const generated = list.map(val => ({
      val,
      x: 10 + Math.random() * 70,
      y: 10 + Math.random() * 70,
      size: 50 + Math.random() * 15
    }));
    setBubbles(generated);
    setNextNum(1);
  };

  const handleBubble = (bubble) => {
    if (!isPlaying) return;
    if (bubble.val === nextNum) {
      playSynthTone(260 + bubble.val * 50);
      if (bubble.val === 6) {
        setScore(score + 1);
        initBubbles();
      } else {
        setNextNum(nextNum + 1);
      }
    } else {
      setIsPlaying(false);
    }
  };

  const startRun = () => {
    setScore(0);
    initBubbles();
    setIsPlaying(true);
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-4">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>SCORE: <span className="text-teal-400 font-black text-sm">{score}</span></div>
        <div>NEXT TARGET: <span className="text-teal-455 font-black text-sm">{nextNum}</span></div>
      </div>
      <div className="relative w-full h-80 bg-slate-950 border border-slate-905 rounded-2xl overflow-hidden">
        {isPlaying && bubbles.map(b => (
          <button
            key={b.val}
            onClick={() => handleBubble(b)}
            className={`absolute rounded-full border font-mono font-black text-xs cursor-pointer flex items-center justify-center transition-all ${
              b.val < nextNum ? 'bg-teal-955/20 border-teal-500/20 text-teal-500/20' :
              'bg-slate-900 border-slate-800 text-slate-200 hover:border-teal-500/40 hover:scale-105 active:scale-95'
            }`}
            style={{
              left: `${b.x}%`,
              top: `${b.y}%`,
              width: `${b.size}px`,
              height: `${b.size}px`
            }}
          >
            {b.val}
          </button>
        ))}
      </div>
      {!isPlaying && (
        <button onClick={startRun} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Start Game
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 4: SHIFTING ARROWS
// ============================================================================
function ShiftingArrowsGame() {
  const directions = ['UP', 'DOWN', 'LEFT', 'RIGHT'];
  const arrowChars = { UP: '↑', DOWN: '↓', LEFT: '←', RIGHT: '→' };
  const [targetDir, setTargetDir] = useState('UP');
  const [currentArrow, setCurrentArrow] = useState('UP');
  const [score, setScore] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [time, setTime] = useState(10);
  const timerRef = useRef(null);

  const nextRound = () => {
    setTargetDir(directions[Math.floor(Math.random() * 4)]);
    setCurrentArrow(directions[Math.floor(Math.random() * 4)]);
  };

  const handleAnswer = (matches) => {
    if (!isPlaying) return;
    const isCorrect = (targetDir === currentArrow) === matches;
    if (isCorrect) {
      setScore(s => s + 1);
      playSynthTone(500);
    } else {
      playSynthTone(180);
    }
    nextRound();
  };

  const startTest = () => {
    setScore(0);
    setTime(10);
    setIsPlaying(true);
    nextRound();
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setTime(t => {
        if (t <= 1) {
          clearInterval(timerRef.current);
          setIsPlaying(false);
          return 0;
        }
        return t - 1;
      });
    }, 1000);
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-350">
        <div>TIMER: <span className="text-teal-400 font-black text-sm">{time}s</span></div>
        <div>SCORE: <span className="text-teal-455 font-black text-sm">{score}</span></div>
      </div>
      <div className="flex flex-col items-center gap-4 bg-slate-950 p-6 rounded-2xl w-full border border-slate-900">
        <span className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">Target Direction</span>
        <span className="text-xl font-black text-teal-400 uppercase tracking-widest font-mono">{targetDir}</span>
        <div className="text-6xl font-black text-slate-100 my-4 select-none">{arrowChars[currentArrow]}</div>
      </div>
      {isPlaying ? (
        <div className="grid grid-cols-2 gap-4 w-full">
          <button onClick={() => handleAnswer(true)} className="py-3.5 bg-emerald-900/10 hover:bg-emerald-600 border border-emerald-500/30 text-emerald-400 hover:text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer">
            Matches
          </button>
          <button onClick={() => handleAnswer(false)} className="py-3.5 bg-rose-900/10 hover:bg-rose-600 border border-rose-500/30 text-rose-455 hover:text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer">
            Mismatch
          </button>
        </div>
      ) : (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Start Game
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 5: TARGET CLICKER
// ============================================================================
function TargetTrackingGame() {
  const [position, setPosition] = useState({ x: 50, y: 50 });
  const [level, setLevel] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [time, setTime] = useState(10);
  const timerRef = useRef(null);

  const moveTarget = () => {
    setPosition({
      x: 10 + Math.random() * 80,
      y: 10 + Math.random() * 80
    });
  };

  const handleTarget = () => {
    if (!isPlaying) return;
    playSynthTone(550 + level * 30);
    setLevel(lvl => lvl + 1);
    moveTarget();
  };

  const startRun = () => {
    setLevel(0);
    setTime(10);
    setIsPlaying(true);
    moveTarget();
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setTime(t => {
        if (t <= 1) {
          clearInterval(timerRef.current);
          setIsPlaying(false);
          return 0;
        }
        return t - 1;
      });
    }, 1000);
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-4">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-350">
        <div>TIME: <span className="text-teal-400 font-black text-sm">{time}s</span></div>
        <div>CLICKS: <span className="text-teal-455 font-black text-sm">{level}</span></div>
      </div>
      <div className="relative w-full h-80 bg-slate-955 border border-slate-900 rounded-2xl overflow-hidden">
        {isPlaying && (
          <button
            onClick={handleTarget}
            className="absolute w-7 h-7 bg-teal-500 hover:bg-teal-400 rounded-full border border-white cursor-pointer transition-all flex items-center justify-center"
            style={{ left: `${position.x}%`, top: `${position.y}%` }}
          />
        )}
      </div>
      {!isPlaying && (
        <button onClick={startRun} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Start Game
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 6: ATTENTION RECALL (SIMON)
// ============================================================================
function SimonSaysGame() {
  const [sequence, setSequence] = useState([]);
  const [userSequence, setUserSequence] = useState([]);
  const [isPlaying, setIsPlaying] = useState(false);
  const [activePad, setActivePad] = useState(null); 
  const [isPlayerTurn, setIsPlayerTurn] = useState(false);
  const [score, setScore] = useState(0);
  const [highScore, setHighScore] = useState(() => parseInt(localStorage.getItem('g_simon_best') || '0'));
  const [gameOver, setGameOver] = useState(false);

  const padColors = [
    'bg-emerald-500/30 border-emerald-500/40 text-emerald-400',
    'bg-rose-500/30 border-rose-500/40 text-rose-455',
    'bg-amber-500/30 border-amber-500/40 text-amber-400',
    'bg-sky-500/30 border-sky-500/40 text-sky-400'
  ];
  
  const padActives = [
    'bg-emerald-450 border-emerald-355 scale-103 shadow-lg shadow-emerald-500/10',
    'bg-rose-450 border-rose-355 scale-103 shadow-lg shadow-rose-500/10',
    'bg-amber-450 border-amber-355 scale-103 shadow-lg shadow-amber-500/10',
    'bg-sky-455 border-sky-355 scale-103 shadow-lg shadow-sky-500/10'
  ];

  const playSeq = async (seq) => {
    setIsPlayerTurn(false);
    for (let i = 0; i < seq.length; i++) {
      await new Promise(r => setTimeout(r, 450));
      setActivePad(seq[i]);
      playSynthTone(200 + seq[i] * 80);
      await new Promise(r => setTimeout(r, 400));
      setActivePad(null);
    }
    await new Promise(r => setTimeout(r, 200));
    setIsPlayerTurn(true);
  };

  const startRun = () => {
    const first = Math.floor(Math.random() * 4);
    setSequence([first]);
    setUserSequence([]);
    setScore(0);
    setGameOver(false);
    setIsPlaying(true);
    playSeq([first]);
  };

  const handlePad = (id) => {
    if (!isPlayerTurn || gameOver) return;
    setActivePad(id);
    playSynthTone(200 + id * 80);
    setTimeout(() => setActivePad(null), 150);

    const nextUser = [...userSequence, id];
    setUserSequence(nextUser);
    
    const curIdx = nextUser.length - 1;
    if (nextUser[curIdx] !== sequence[curIdx]) {
      setGameOver(true);
      setIsPlaying(false);
      if (score > highScore) {
        setHighScore(score);
        localStorage.setItem('g_simon_best', String(score));
      }
      return;
    }

    if (nextUser.length === sequence.length) {
      setScore(s => s + 1);
      setUserSequence([]);
      const nextSeq = [...sequence, Math.floor(Math.random() * 4)];
      setSequence(nextSeq);
      setTimeout(() => playSeq(nextSeq), 700);
    }
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-4 select-none">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold text-slate-350">
        <div>SCORE: <span className="text-teal-400 font-black text-sm">{score}</span></div>
        <div>BEST: <span className="text-slate-200 text-sm">{highScore}</span></div>
        <div>TURN: <span className="text-teal-455 font-black text-sm">{isPlayerTurn ? 'PLAY' : 'WATCH'}</span></div>
      </div>
      <div className="grid grid-cols-2 gap-4 w-full aspect-square">
        {[0,1,2,3].map(id => (
          <button
            key={id}
            disabled={!isPlayerTurn || gameOver}
            onClick={() => handlePad(id)}
            className={`rounded-2xl border cursor-pointer transition-all duration-150 active:scale-95 ${
              activePad === id ? padActives[id] : padColors[id]
            }`}
            style={{ minHeight: '110px' }}
          />
        ))}
      </div>
      {!isPlaying && (
        <button onClick={startRun} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          {gameOver ? 'Try Again' : 'Start recall'}
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 7: MATRIX MEMORY
// ============================================================================
function MatrixMemoryGame() {
  const [level, setLevel] = useState(1);
  const [activeTiles, setActiveTiles] = useState([]);
  const [selectedTiles, setSelectedTiles] = useState([]);
  const [gameState, setGameState] = useState('idle'); 
  const [bestLevel, setBestLevel] = useState(() => parseInt(localStorage.getItem('g_matrix_best') || '1'));

  const generateLevel = (lvl) => {
    const numTiles = Math.min(3 + lvl, 10);
    const indices = [];
    while (indices.length < numTiles) {
      const idx = Math.floor(Math.random() * 16);
      if (!indices.includes(idx)) indices.push(idx);
    }
    setActiveTiles(indices);
    setSelectedTiles([]);
    setGameState('showing');
    setTimeout(() => setGameState('playing'), 1200);
  };

  const handleTile = (idx) => {
    if (gameState !== 'playing') return;
    if (selectedTiles.includes(idx)) return;

    if (activeTiles.includes(idx)) {
      const nextSel = [...selectedTiles, idx];
      setSelectedTiles(nextSel);
      playSynthTone(400 + nextSel.length * 30);
      if (nextSel.length === activeTiles.length) {
        setGameState('win');
        setLevel(l => l + 1);
        if (level + 1 > bestLevel) {
          setBestLevel(level + 1);
          localStorage.setItem('g_matrix_best', String(level + 1));
        }
      }
    } else {
      setGameState('lose');
      playSynthTone(180);
    }
  };

  const startRun = () => {
    setLevel(1);
    generateLevel(1);
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-4">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold text-slate-350">
        <div>STAGE: <span className="text-teal-400 font-black text-sm">{level}</span></div>
        <div>BEST: <span className="text-slate-200 text-sm">Level {bestLevel}</span></div>
        <div>STATE: <span className="text-teal-455 font-black text-[10px] uppercase tracking-wider">{gameState}</span></div>
      </div>
      <div className="grid grid-cols-4 gap-2.5 w-full aspect-square bg-slate-955 p-2.5 border border-slate-900 rounded-3xl">
        {Array.from({ length: 16 }).map((_, idx) => {
          let tileClass = 'bg-slate-900 border-slate-850';
          if (gameState === 'showing' && activeTiles.includes(idx)) {
            tileClass = 'bg-emerald-555 border-emerald-455 scale-95';
          } else if (gameState === 'playing' && selectedTiles.includes(idx)) {
            tileClass = 'bg-emerald-500/20 border-emerald-555 text-emerald-455';
          } else if (gameState === 'win' && activeTiles.includes(idx)) {
            tileClass = 'bg-emerald-555 border-emerald-405';
          } else if (gameState === 'lose') {
            if (activeTiles.includes(idx) && !selectedTiles.includes(idx)) {
              tileClass = 'bg-amber-500 border-amber-400';
            } else if (selectedTiles.includes(idx)) {
              tileClass = 'bg-emerald-500/20 border-emerald-555';
            } else {
              tileClass = 'bg-rose-955/20 border-rose-500';
            }
          }
          return (
            <button
              key={idx}
              disabled={gameState !== 'playing'}
              onClick={() => handleTile(idx)}
              className={`rounded-xl border cursor-pointer transition-all ${tileClass}`}
            />
          );
        })}
      </div>
      {gameState === 'idle' || gameState === 'lose' ? (
        <button onClick={startRun} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Start Memory Match
        </button>
      ) : gameState === 'win' ? (
        <button onClick={() => generateLevel(level)} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Next Stage
        </button>
      ) : (
        <button disabled className="w-full py-3.5 bg-slate-900 border border-slate-800 text-slate-500 font-bold text-xs uppercase tracking-widest rounded-xl">
          Recall active tiles
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 8: DIGIT SPAN
// ============================================================================
function DigitSpanGame() {
  const [digits, setDigits] = useState('');
  const [inputVal, setInputVal] = useState('');
  const [level, setLevel] = useState(4);
  const [gameState, setGameState] = useState('idle'); 
  const [score, setScore] = useState(0);

  const startLevel = (lvl) => {
    let result = '';
    for (let i = 0; i < lvl; i++) {
      result += Math.floor(Math.random() * 10);
    }
    setDigits(result);
    setInputVal('');
    setGameState('showing');
    setTimeout(() => {
      setGameState('input');
    }, 1500 + lvl * 150);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (inputVal === digits) {
      playSynthTone(550);
      setScore(s => s + 1);
      setLevel(l => l + 1);
      setGameState('win');
    } else {
      playSynthTone(180);
      setGameState('lose');
    }
  };

  const startNew = () => {
    setScore(0);
    setLevel(4);
    startLevel(4);
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-5 select-none">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold text-slate-355">
        <div>SEQUENCE LEVEL: <span className="text-teal-400 font-black">{level} Digits</span></div>
        <div>SCORE: <span className="text-teal-455 font-black">{score}</span></div>
      </div>
      <div className="flex flex-col items-center justify-center bg-slate-950 p-6 rounded-2xl w-full border border-slate-905 h-44">
        {gameState === 'showing' ? (
          <div className="text-4xl font-black text-slate-100 tracking-widest font-mono animate-pulse">{digits}</div>
        ) : gameState === 'input' ? (
          <form onSubmit={handleSubmit} className="w-full space-y-4">
            <input
              type="text"
              pattern="[0-9]*"
              value={inputVal}
              onChange={e => setInputVal(e.target.value)}
              placeholder="Type sequence..."
              className="w-full bg-slate-900 border-2 border-slate-800 focus:border-teal-500 rounded-xl px-4 py-3 text-center text-slate-100 font-mono font-black text-lg tracking-widest outline-none"
              autoFocus
            />
            <button type="submit" className="w-full py-2.5 bg-teal-650 hover:bg-teal-600 text-white rounded-xl text-xs font-black uppercase tracking-widest cursor-pointer transition-all">Submit</button>
          </form>
        ) : gameState === 'win' ? (
          <div className="text-center space-y-2">
            <span className="text-emerald-450 font-black text-lg uppercase tracking-wider block">Correct Recall!</span>
            <button onClick={() => startLevel(level)} className="px-5 py-2 bg-slate-900 border border-slate-850 hover:border-teal-500/20 text-teal-400 rounded-xl text-xs font-bold uppercase transition-all cursor-pointer">Proceed</button>
          </div>
        ) : (
          <div className="text-center space-y-2">
            <span className="text-rose-455 font-black text-lg uppercase tracking-wider block">Wrong Answer</span>
            <p className="text-xs text-slate-500">Correct sequence was: <span className="font-mono text-slate-300 font-bold">{digits}</span></p>
            <button onClick={startNew} className="px-5 py-2 bg-slate-900 border border-slate-850 hover:border-teal-500/20 text-teal-400 rounded-xl text-xs font-bold uppercase transition-all cursor-pointer mt-2">Try Again</button>
          </div>
        )}
      </div>
      {gameState === 'idle' && (
        <button onClick={startNew} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Game</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 9: TONE RECALL
// ============================================================================
function ToneMemoryGame() {
  const tones = [261.63, 293.66, 329.63, 349.23]; // C4, D4, E4, F4
  const colors = ['bg-emerald-500/30', 'bg-rose-500/30', 'bg-amber-500/30', 'bg-sky-500/30'];
  const activeStyles = ['bg-emerald-455 scale-95 shadow-md shadow-emerald-500/10', 'bg-rose-455 scale-95 shadow-md shadow-rose-500/10', 'bg-amber-455 scale-95 shadow-md shadow-amber-500/10', 'bg-sky-455 scale-95 shadow-md shadow-sky-500/10'];
  const [sequence, setSequence] = useState([]);
  const [userSequence, setUserSequence] = useState([]);
  const [isPlaying, setIsPlaying] = useState(false);
  const [activeTone, setActiveTone] = useState(null);
  const [isPlayerTurn, setIsPlayerTurn] = useState(false);
  const [score, setScore] = useState(0);

  const playSequence = async (seq) => {
    setIsPlayerTurn(false);
    for (let i = 0; i < seq.length; i++) {
      await new Promise(r => setTimeout(r, 450));
      setActiveTone(seq[i]);
      playSynthTone(tones[seq[i]]);
      await new Promise(r => setTimeout(r, 400));
      setActiveTone(null);
    }
    await new Promise(r => setTimeout(r, 200));
    setIsPlayerTurn(true);
  };

  const startRun = () => {
    const first = Math.floor(Math.random() * 4);
    setSequence([first]);
    setUserSequence([]);
    setScore(0);
    setIsPlaying(true);
    playSequence([first]);
  };

  const handleTone = (id) => {
    if (!isPlayerTurn) return;
    setActiveTone(id);
    playSynthTone(tones[id]);
    setTimeout(() => setActiveTone(null), 150);

    const nextUser = [...userSequence, id];
    setUserSequence(nextUser);
    
    const curIdx = nextUser.length - 1;
    if (nextUser[curIdx] !== sequence[curIdx]) {
      setIsPlaying(false);
      alert(`Wrong pitch sequence. Game Over! Score: ${score}`);
      return;
    }

    if (nextUser.length === sequence.length) {
      setScore(s => s + 1);
      setUserSequence([]);
      const nextSeq = [...sequence, Math.floor(Math.random() * 4)];
      setSequence(nextSeq);
      setTimeout(() => playSequence(nextSeq), 700);
    }
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-5">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold text-slate-350">
        <div>SCORE: <span className="text-teal-400 font-black">{score}</span></div>
        <div>MODE: <span className="text-teal-455 font-black uppercase">{isPlayerTurn ? 'REPLAY' : 'LISTEN'}</span></div>
      </div>
      <div className="grid grid-cols-4 gap-3.5 w-full aspect-square bg-slate-950 p-3.5 border border-slate-900 rounded-3xl">
        {[0,1,2,3].map(id => (
          <button
            key={id}
            disabled={!isPlayerTurn}
            onClick={() => handleTone(id)}
            className={`rounded-2xl border-2 border-slate-800 transition-all cursor-pointer flex flex-col items-center justify-center text-slate-400 font-mono font-bold ${
              activeTone === id ? activeStyles[id] : colors[id]
            }`}
          >
            <span>Tone</span>
            <span className="text-[10px] opacity-60 mt-1">#{id+1}</span>
          </button>
        ))}
      </div>
      {!isPlaying && (
        <button onClick={startRun} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Run</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 10: PATTERN TRACER
// ============================================================================
function PathTracerGame() {
  const [activePath, setActivePath] = useState([]);
  const [selectedPath, setSelectedPath] = useState([]);
  const [gameState, setGameState] = useState('idle'); 
  const [level, setLevel] = useState(1);

  const generatePath = (lvl) => {
    const len = Math.min(3 + lvl, 6);
    const indices = [];
    while (indices.length < len) {
      const idx = Math.floor(Math.random() * 9);
      if (!indices.includes(idx)) indices.push(idx);
    }
    setActivePath(indices);
    setSelectedPath([]);
    setGameState('showing');
    setTimeout(() => {
      setGameState('playing');
    }, 1500 + len * 200);
  };

  const handleNode = (idx) => {
    if (gameState !== 'playing') return;
    const targetIdx = selectedPath.length;
    if (activePath[targetIdx] === idx) {
      const nextPath = [...selectedPath, idx];
      setSelectedPath(nextPath);
      playSynthTone(300 + nextPath.length * 50);
      if (nextPath.length === activePath.length) {
        setGameState('win');
        setLevel(l => l + 1);
      }
    } else {
      setGameState('lose');
      playSynthTone(180);
    }
  };

  const startRun = () => {
    setLevel(1);
    generatePath(1);
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-4">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold text-slate-350">
        <div>STAGE LEVEL: <span className="text-teal-400 font-black">{level}</span></div>
        <div>STATE: <span className="text-teal-455 font-black uppercase tracking-wider">{gameState}</span></div>
      </div>
      <div className="grid grid-cols-3 gap-4 w-full aspect-square bg-slate-950 p-4 border border-slate-900 rounded-3xl">
        {Array.from({ length: 9 }).map((_, idx) => {
          let nodeClass = 'bg-slate-900 border-slate-800 text-slate-600';
          if (gameState === 'showing') {
            const pathIdx = activePath.indexOf(idx);
            if (pathIdx !== -1) {
              nodeClass = 'bg-emerald-555 border-emerald-455 text-white scale-98 shadow';
            }
          } else if (gameState === 'playing') {
            if (selectedPath.includes(idx)) {
              nodeClass = 'bg-emerald-500/20 border-emerald-555 text-emerald-400';
            } else {
              nodeClass = 'bg-slate-905 hover:bg-slate-850 hover:border-slate-700 border-slate-800 cursor-pointer';
            }
          } else if (gameState === 'win') {
            if (activePath.includes(idx)) nodeClass = 'bg-emerald-555 border-emerald-455 text-white';
          } else if (gameState === 'lose') {
            nodeClass = 'bg-rose-955/20 border-rose-500 text-rose-455 scale-95';
          }

          const activePathIndex = activePath.indexOf(idx);

          return (
            <button
              key={idx}
              disabled={gameState !== 'playing'}
              onClick={() => handleNode(idx)}
              className={`rounded-2xl border-2 text-xs font-mono font-bold flex items-center justify-center transition-all ${nodeClass}`}
            >
              {gameState === 'showing' && activePathIndex !== -1 ? activePathIndex + 1 : ''}
              {gameState === 'playing' && selectedPath.includes(idx) ? selectedPath.indexOf(idx) + 1 : ''}
            </button>
          );
        })}
      </div>
      {gameState === 'idle' || gameState === 'lose' ? (
        <button onClick={startRun} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-655 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Trace</button>
      ) : gameState === 'win' ? (
        <button onClick={() => generatePath(level)} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-655 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Next Stage</button>
      ) : (
        <button disabled className="w-full py-3.5 bg-slate-900 border border-slate-800 text-slate-500 font-bold text-xs uppercase tracking-widest rounded-xl">Trace pattern shown</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 11: STROOP TEST
// ============================================================================
function StroopGame() {
  const wordPiles = [
    { text: 'RED', color: 'text-rose-550', rgb: 'Red' },
    { text: 'BLUE', color: 'text-sky-455', rgb: 'Blue' },
    { text: 'GREEN', color: 'text-emerald-455', rgb: 'Green' },
    { text: 'YELLOW', color: 'text-amber-400', rgb: 'Yellow' }
  ];
  const colorOptions = ['Red', 'Blue', 'Green', 'Yellow'];
  const [currentQuery, setCurrentQuery] = useState(null);
  const [score, setScore] = useState(0);
  const [time, setTime] = useState(10);
  const [isPlaying, setIsPlaying] = useState(false);
  const timerRef = useRef(null);

  const nextQuestion = () => {
    const textIdx = Math.floor(Math.random() * 4);
    const colorIdx = Math.floor(Math.random() * 4);
    setCurrentQuery({
      text: wordPiles[textIdx].text,
      color: wordPiles[colorIdx].color,
      correctColor: wordPiles[colorIdx].rgb
    });
  };

  const handleAnswer = (option) => {
    if (!isPlaying) return;
    if (option === currentQuery.correctColor) {
      setScore(s => s + 1);
      playSynthTone(550);
    } else {
      playSynthTone(180);
    }
    nextQuestion();
  };

  const startTest = () => {
    setScore(0);
    setTime(10);
    setIsPlaying(true);
    nextQuestion();
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setTime(t => {
        if (t <= 1) {
          clearInterval(timerRef.current);
          setIsPlaying(false);
          return 0;
        }
        return t - 1;
      });
    }, 1000);
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>TIMER: <span className="text-teal-400 font-black text-sm">{time}s</span></div>
        <div>SCORE: <span className="text-teal-455 font-black text-sm">{score}</span></div>
      </div>
      <div className="flex flex-col items-center justify-center bg-slate-950 p-6 rounded-2xl w-full border border-slate-900 h-44">
        {isPlaying && currentQuery ? (
          <div className="space-y-1.5 text-center">
            <span className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">IDENTIFY COLOR</span>
            <div className={`text-4xl font-black tracking-widest select-none ${currentQuery.color}`}>{currentQuery.text}</div>
          </div>
        ) : (
          <span className="text-slate-500 font-bold text-xs uppercase tracking-wider">Tap Start to Begin</span>
        )}
      </div>
      {isPlaying ? (
        <div className="grid grid-cols-2 gap-3 w-full">
          {colorOptions.map(opt => (
            <button
              key={opt}
              onClick={() => handleAnswer(opt)}
              className="py-3 bg-slate-900/60 hover:bg-teal-650/15 border border-slate-850 hover:border-teal-500/35 text-slate-300 hover:text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer"
            >
              {opt}
            </button>
          ))}
        </div>
      ) : (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Stroop Game</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 12: MATH MARATHON
// ============================================================================
function QuickMathGame() {
  const [expr, setExpr] = useState('');
  const [correctAns, setCorrectAns] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [score, setScore] = useState(0);
  const [time, setTime] = useState(2500); 
  const timerRef = useRef(null);

  const nextQuestion = () => {
    const ops = ['+', '-', '*'];
    const op = ops[Math.floor(Math.random() * 3)];
    let n1 = Math.floor(Math.random() * 15) + 2;
    let n2 = Math.floor(Math.random() * 10) + 2;
    if (op === '*') {
      n1 = Math.floor(Math.random() * 9) + 2;
      n2 = Math.floor(Math.random() * 9) + 2;
    }
    setExpr(`${n1} ${op} ${n2}`);
    let ans = 0;
    if (op === '+') ans = n1 + n2;
    else if (op === '-') ans = n1 - n2;
    else if (op === '*') ans = n1 * n2;
    setCorrectAns(ans);
    
    // Set 2.5 second timer tick
    const start = Date.now();
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      const elapsed = Date.now() - start;
      const remaining = Math.max(0, 2500 - elapsed);
      setTime(remaining);
      if (remaining <= 0) {
        clearInterval(timerRef.current);
        setIsPlaying(false);
        playSynthTone(180);
      }
    }, 15);
  };

  const handleAnswer = (val) => {
    if (!isPlaying) return;
    clearInterval(timerRef.current);
    if (val === correctAns) {
      setScore(s => s + 1);
      playSynthTone(550);
      nextQuestion();
    } else {
      setIsPlaying(false);
      playSynthTone(180);
    }
  };

  const startTest = () => {
    setScore(0);
    setIsPlaying(true);
    nextQuestion();
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  // Generate 4 multiple choice options
  const generateOptions = () => {
    const set = new Set([correctAns]);
    while (set.size < 4) {
      const offset = (Math.floor(Math.random() * 5) + 1) * (Math.random() > 0.5 ? 1 : -1);
      set.add(correctAns + offset);
    }
    return Array.from(set).sort(() => Math.random() - 0.5);
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>TIMER Remaining: <span className="text-teal-400 font-black text-sm">{(time/1000).toFixed(2)}s</span></div>
        <div>SCORE: <span className="text-teal-455 font-black text-sm">{score}</span></div>
      </div>
      <div className="relative w-full h-1.5 bg-slate-800 rounded-full overflow-hidden">
        <div className="h-full bg-teal-500 transition-all" style={{ width: `${(time / 2500) * 100}%` }} />
      </div>
      <div className="flex items-center justify-center bg-slate-950 p-6 rounded-2xl w-full border border-slate-900 h-36">
        {isPlaying ? (
          <div className="text-4xl font-black text-slate-100 font-mono tracking-wide">{expr} = ?</div>
        ) : (
          <span className="text-slate-500 font-bold text-xs uppercase tracking-wider">Solve math under pressure</span>
        )}
      </div>
      {isPlaying ? (
        <div className="grid grid-cols-2 gap-3 w-full">
          {generateOptions().map(opt => (
            <button
              key={opt}
              onClick={() => handleAnswer(opt)}
              className="py-3 bg-slate-900/60 hover:bg-teal-650/15 border border-slate-855 hover:border-teal-500/35 text-slate-200 hover:text-white rounded-xl text-xs font-mono font-bold transition-all cursor-pointer"
            >
              {opt}
            </button>
          ))}
        </div>
      ) : (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Math Marathon</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 13: COLOR MATCHER
// ============================================================================
function ColorSwitchGame() {
  const listColors = ['bg-rose-500', 'bg-sky-500', 'bg-emerald-500', 'bg-amber-400'];
  const [prevColor, setPrevColor] = useState(null);
  const [currColor, setCurrColor] = useState(null);
  const [score, setScore] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [time, setTime] = useState(10);
  const timerRef = useRef(null);

  const nextColor = () => {
    setPrevColor(currColor);
    const chosen = Math.floor(Math.random() * 4);
    setCurrColor(chosen);
  };

  const handleAnswer = (matches) => {
    if (!isPlaying) return;
    if (prevColor === null) {
      nextColor();
      return;
    }
    const isCorrect = (prevColor === currColor) === matches;
    if (isCorrect) {
      setScore(s => s + 1);
      playSynthTone(550);
    } else {
      playSynthTone(180);
    }
    nextColor();
  };

  const startTest = () => {
    setScore(0);
    setTime(10);
    setPrevColor(null);
    const first = Math.floor(Math.random() * 4);
    setCurrColor(first);
    setIsPlaying(true);
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setTime(t => {
        if (t <= 1) {
          clearInterval(timerRef.current);
          setIsPlaying(false);
          return 0;
        }
        return t - 1;
      });
    }, 1000);
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>TIMER: <span className="text-teal-400 font-black text-sm">{time}s</span></div>
        <div>SCORE: <span className="text-teal-455 font-black text-sm">{score}</span></div>
      </div>
      <div className="flex flex-col items-center justify-center bg-slate-950 p-6 rounded-2xl w-full border border-slate-900 h-44">
        {isPlaying && currColor !== null ? (
          <div className="space-y-4 text-center flex flex-col items-center w-full">
            <span className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">DOES THIS MATCH THE PREVIOUS COLOR?</span>
            <div className={`w-20 h-20 rounded-2xl border-2 border-white/10 ${listColors[currColor]}`} />
          </div>
        ) : (
          <span className="text-slate-500 font-bold text-xs uppercase tracking-wider">Tap Start to Begin</span>
        )}
      </div>
      {isPlaying ? (
        <div className="grid grid-cols-2 gap-4 w-full">
          <button onClick={() => handleAnswer(true)} className="py-3.5 bg-emerald-900/10 hover:bg-emerald-600 border border-emerald-500/30 text-emerald-400 hover:text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer">
            Yes (Matches)
          </button>
          <button onClick={() => handleAnswer(false)} className="py-3.5 bg-rose-900/10 hover:bg-rose-600 border border-rose-500/30 text-rose-455 hover:text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer">
            No
          </button>
        </div>
      ) : (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Game</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 14: ANAGRAM FOCUS
// ============================================================================
function AnagramSolverGame() {
  const vocabulary = [
    { clean: 'FOCUS', scram: 'O U C S F' },
    { clean: 'STUDY', scram: 'U D T Y S' },
    { clean: 'TIMER', scram: 'M E T R I' },
    { clean: 'BRAIN', scram: 'R I B A N' },
    { clean: 'EXAMS', scram: 'M X S E A' },
    { clean: 'CHILL', scram: 'H L C L I' }
  ];
  const [activeWord, setActiveWord] = useState(null);
  const [inputVal, setInputVal] = useState('');
  const [isPlaying, setIsPlaying] = useState(false);
  const [score, setScore] = useState(0);

  const nextWord = () => {
    const chosen = vocabulary[Math.floor(Math.random() * vocabulary.length)];
    setActiveWord(chosen);
    setInputVal('');
  };

  const handleCheck = (e) => {
    e.preventDefault();
    if (!isPlaying) return;
    if (inputVal.trim().toUpperCase() === activeWord.clean) {
      playSynthTone(550);
      setScore(s => s + 1);
      nextWord();
    } else {
      playSynthTone(180);
    }
  };

  const startTest = () => {
    setScore(0);
    setIsPlaying(true);
    nextWord();
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-5">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold text-slate-355">
        <div>SOLVED WORDS: <span className="text-teal-400 font-black text-sm">{score}</span></div>
      </div>
      <div className="flex flex-col items-center justify-center bg-slate-955 p-6 rounded-2xl w-full border border-slate-900 h-40">
        {isPlaying && activeWord ? (
          <div className="text-center space-y-3 w-full">
            <span className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">UNSCRAMBLE THE WORD</span>
            <div className="text-3xl font-black text-teal-400 font-mono tracking-widest">{activeWord.scram}</div>
          </div>
        ) : (
          <span className="text-slate-500 font-bold text-xs uppercase tracking-wider">Unscramble concentration words</span>
        )}
      </div>
      {isPlaying ? (
        <form onSubmit={handleCheck} className="w-full space-y-3">
          <input
            type="text"
            value={inputVal}
            onChange={e => setInputVal(e.target.value)}
            placeholder="Type word..."
            className="w-full bg-slate-900 border-2 border-slate-800 focus:border-teal-500 rounded-xl px-4 py-3 text-center text-slate-100 font-extrabold text-sm uppercase tracking-widest outline-none"
            autoFocus
          />
          <button type="submit" className="w-full py-2.5 bg-teal-650 hover:bg-teal-600 text-white rounded-xl text-xs font-black uppercase tracking-widest cursor-pointer transition-all">Check Anagram</button>
        </form>
      ) : (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Anagram Game</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 15: MISSING NUMBER
// ============================================================================
function MissingNumberGame() {
  const [sequenceText, setSequenceText] = useState('');
  const [missingVal, setMissingVal] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [score, setScore] = useState(0);

  const generateSequence = () => {
    const types = ['add', 'mul', 'fibo'];
    const type = types[Math.floor(Math.random() * 3)];
    let seq = [];
    if (type === 'add') {
      const step = Math.floor(Math.random() * 5) + 2;
      let start = Math.floor(Math.random() * 10) + 1;
      for (let i = 0; i < 5; i++) {
        seq.push(start);
        start += step;
      }
    } else if (type === 'mul') {
      const mul = Math.random() > 0.5 ? 2 : 3;
      let start = Math.floor(Math.random() * 4) + 1;
      for (let i = 0; i < 5; i++) {
        seq.push(start);
        start *= mul;
      }
    } else {
      seq = [1, 2, 3, 5, 8];
      const startOffset = Math.floor(Math.random() * 4) + 1;
      seq = seq.map(x => x * startOffset);
    }

    const missingIdx = Math.floor(Math.random() * 3) + 1; 
    setMissingVal(seq[missingIdx]);
    
    const formatted = [...seq];
    formatted[missingIdx] = '?';
    setSequenceText(formatted.join(', '));
  };

  const handleAnswer = (val) => {
    if (!isPlaying) return;
    if (val === missingVal) {
      setScore(s => s + 1);
      playSynthTone(550);
      generateSequence();
    } else {
      setIsPlaying(false);
      playSynthTone(180);
    }
  };

  const startTest = () => {
    setScore(0);
    setIsPlaying(true);
    generateSequence();
  };

  const generateOptions = () => {
    const set = new Set([missingVal]);
    while (set.size < 4) {
      const offset = (Math.floor(Math.random() * 4) + 1) * (Math.random() > 0.5 ? 1 : -1);
      set.add(missingVal + offset);
    }
    return Array.from(set).sort((a,b) => a-b);
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>SCORE: <span className="text-teal-400 font-black text-sm">{score}</span></div>
      </div>
      <div className="flex flex-col items-center justify-center bg-slate-955 p-6 rounded-2xl w-full border border-slate-900 h-36">
        {isPlaying ? (
          <div className="text-center space-y-3 w-full">
            <span className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">IDENTIFY MISSING TERM</span>
            <div className="text-3xl font-black text-teal-400 font-mono tracking-widest">{sequenceText}</div>
          </div>
        ) : (
          <span className="text-slate-500 font-bold text-xs uppercase tracking-wider">Solve numerical progression sequences</span>
        )}
      </div>
      {isPlaying ? (
        <div className="grid grid-cols-4 gap-2 w-full">
          {generateOptions().map(opt => (
            <button
              key={opt}
              onClick={() => handleAnswer(opt)}
              className="py-3 bg-slate-900/60 hover:bg-teal-650/15 border border-slate-850 hover:border-teal-500/35 text-slate-200 hover:text-white rounded-xl text-xs font-mono font-bold transition-all cursor-pointer"
            >
              {opt}
            </button>
          ))}
        </div>
      ) : (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-555 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start Game</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 16: ALERTNESS CHECK
// ============================================================================
function ReactionTimerGame() {
  const [gameState, setGameState] = useState('idle');
  const [reaction, setReaction] = useState(0);
  const [best, setBest] = useState(() => parseInt(localStorage.getItem('g_reaction_best') || '9999'));
  const timerRef = useRef(null);
  const startRef = useRef(0);

  const startTest = () => {
    setGameState('wait');
    const delay = Math.random() * 3000 + 1500;
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => {
      setGameState('click');
      startRef.current = Date.now();
    }, delay);
  };

  const handleClick = () => {
    if (gameState === 'wait') {
      clearTimeout(timerRef.current);
      setGameState('early');
      playSynthTone(180);
    } else if (gameState === 'click') {
      const elapsed = Date.now() - startRef.current;
      setReaction(elapsed);
      setGameState('result');
      playSynthTone(550);
      if (elapsed < best) {
        setBest(elapsed);
        localStorage.setItem('g_reaction_best', String(elapsed));
      }
    }
  };

  useEffect(() => { return () => clearTimeout(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-5">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>BEST SPEED: <span className="text-teal-400 font-black text-sm">{best === 9999 ? 'N/A' : `${best}ms`}</span></div>
      </div>
      <div
        onClick={handleClick}
        className={`w-full h-64 rounded-2xl border-2 flex flex-col items-center justify-center text-center p-6 cursor-pointer select-none transition-all ${
          gameState === 'idle' ? 'bg-slate-955 border-slate-900 hover:border-teal-500/30 text-slate-400' :
          gameState === 'wait' ? 'bg-rose-955/20 border-rose-500/30 text-rose-455 animate-pulse' :
          gameState === 'click' ? 'bg-emerald-500/10 border-emerald-400 text-emerald-400 scale-98 shadow shadow-emerald-500/10' :
          gameState === 'result' ? 'bg-teal-955/15 border-teal-400 text-teal-400' : 'bg-amber-955/20 border-amber-500/30 text-amber-500'
        }`}
      >
        {gameState === 'idle' && (
          <div className="space-y-2 pointer-events-none">
            <Play size={36} className="mx-auto text-teal-450" />
            <h4 className="text-sm font-extrabold text-slate-100 uppercase">CLICK BOX TO BEGIN SPEED TEST</h4>
          </div>
        )}
        {gameState === 'wait' && (
          <div className="space-y-1">
            <h4 className="text-lg font-black uppercase tracking-wider animate-pulse">Wait for green...</h4>
          </div>
        )}
        {gameState === 'click' && (
          <div className="space-y-1">
            <h4 className="text-2xl font-black uppercase tracking-widest">TAP NOW!</h4>
          </div>
        )}
        {gameState === 'result' && (
          <div className="space-y-2">
            <h4 className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">Reaction Speed</h4>
            <p className="text-4xl font-black text-slate-100 font-mono">{reaction}ms</p>
            <p className="text-[10px] uppercase font-bold text-teal-500 mt-2">Tap to start another trial</p>
          </div>
        )}
        {gameState === 'early' && (
          <div className="space-y-2">
            <AlertTriangle size={36} className="mx-auto text-amber-500" />
            <h4 className="text-lg font-black uppercase text-amber-500">Too Early!</h4>
            <p className="text-[10px] text-slate-500">Wait for the screen to turn green.</p>
          </div>
        )}
      </div>
      {(gameState === 'result' || gameState === 'early' || gameState === 'idle') && (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-555 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Start Test
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 17: TIME PRECISION
// ============================================================================
function TimePrecisionGame() {
  const [gameState, setGameState] = useState('idle'); 
  const [elapsed, setElapsed] = useState(0);
  const [score, setScore] = useState(null);
  const startRef = useRef(0);
  const timerRef = useRef(null);

  const startStopwatch = () => {
    setGameState('running');
    setScore(null);
    startRef.current = Date.now();
    timerRef.current = setInterval(() => {
      setElapsed((Date.now() - startRef.current) / 1000);
    }, 15);
  };

  const stopStopwatch = () => {
    clearInterval(timerRef.current);
    const stopTime = (Date.now() - startRef.current) / 1000;
    setElapsed(stopTime);
    
    const difference = Math.abs(1.000 - stopTime);
    setScore(difference.toFixed(3));
    setGameState('result');
    if (difference <= 0.05) {
      playSynthTone(750);
    } else {
      playSynthTone(300);
    }
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="flex flex-col items-center justify-center bg-slate-950 p-6 rounded-2xl w-full border border-slate-900 h-44 select-none">
        <span className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">STOP EXACTLY AT 1.000s</span>
        <div className="text-5xl font-black text-slate-100 font-mono tracking-widest my-3">
          {gameState === 'running' ? '?.???' : elapsed.toFixed(3)}s
        </div>
        {gameState === 'result' && (
          <div className="text-center space-y-1">
            <span className="text-slate-500 font-bold text-xs uppercase">Variance Offset</span>
            <p className={`text-sm font-black font-mono ${parseFloat(score) <= 0.05 ? 'text-emerald-400' : 'text-amber-500'}`}>
              ± {score}s
            </p>
          </div>
        )}
      </div>
      {gameState === 'running' ? (
        <button onClick={stopStopwatch} className="w-full py-4 bg-rose-600 hover:bg-rose-500 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer shadow-md">
          STOP
        </button>
      ) : (
        <button onClick={startStopwatch} className="w-full py-4 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer shadow-md">
          START TIMER
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 18: CLICK RUSH
// ============================================================================
function ClickRushGame() {
  const [clicks, setClicks] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [time, setTime] = useState(10);
  const timerRef = useRef(null);

  const handleTap = () => {
    if (!isPlaying) return;
    setClicks(c => c + 1);
    playSynthTone(400 + clicks * 5);
  };

  const startRun = () => {
    setClicks(0);
    setTime(10);
    setIsPlaying(true);
    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setTime(t => {
        if (t <= 1) {
          clearInterval(timerRef.current);
          setIsPlaying(false);
          return 0;
        }
        return t - 1;
      });
    }, 1000);
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-5">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>TIMER Remaining: <span className="text-teal-400 font-black text-sm">{time}s</span></div>
        <div>SCORE: <span className="text-teal-455 font-black text-sm">{clicks} Click</span></div>
      </div>
      <div
        onClick={handleTap}
        className={`w-full h-56 rounded-2xl border-2 flex flex-col items-center justify-center text-center p-6 transition-all select-none ${
          isPlaying ? 'bg-teal-950/10 border-teal-500/35 cursor-pointer active:scale-98' : 'bg-slate-955 border-slate-900 text-slate-505'
        }`}
      >
        {isPlaying ? (
          <h4 className="text-xl font-black uppercase text-teal-400 tracking-wider">TAP HERE AS FAST AS POSSIBLE!</h4>
        ) : (
          <div className="space-y-1">
            <h4 className="text-sm font-bold uppercase text-slate-450">Rush Click Challenge</h4>
            <p className="text-[10px]">Test your tap speed inside 10 seconds.</p>
          </div>
        )}
      </div>
      {!isPlaying && (
        <button onClick={startRun} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Start Rush
        </button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 19: VISUAL N-BACK LITE
// ============================================================================
function DualNBackGame() {
  const [position, setPosition] = useState(0);
  const [prevPosition, setPrevPosition] = useState(null);
  const [score, setScore] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [trials, setTrials] = useState(0);

  const nextTrial = () => {
    setPrevPosition(position);
    const nextPos = Math.floor(Math.random() * 9);
    setPosition(nextPos);
    setTrials(t => t + 1);
  };

  const handleDecision = (matches) => {
    if (!isPlaying) return;
    if (prevPosition === null) {
      nextTrial();
      return;
    }
    const isCorrect = (prevPosition === position) === matches;
    if (isCorrect) {
      setScore(s => s + 1);
      playSynthTone(550);
    } else {
      playSynthTone(180);
    }
    nextTrial();
  };

  const startTest = () => {
    setScore(0);
    setTrials(0);
    setPrevPosition(null);
    setPosition(Math.floor(Math.random() * 9));
    setIsPlaying(true);
  };

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-4">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>SCORE: <span className="text-teal-400 font-black text-sm">{score}/{trials}</span></div>
        <div>N-BACK LEVEL: <span className="text-teal-455 font-black text-sm">1-Back</span></div>
      </div>
      <div className="grid grid-cols-3 gap-3 w-full aspect-square bg-slate-950 p-3.5 border border-slate-900 rounded-3xl">
        {Array.from({ length: 9 }).map((_, idx) => (
          <div
            key={idx}
            className={`rounded-2xl border-2 transition-all duration-150 ${
              isPlaying && position === idx
                ? 'bg-teal-555 border-teal-400 scale-95 shadow-md shadow-teal-500/15'
                : 'bg-slate-900 border-slate-850'
            }`}
          />
        ))}
      </div>
      {isPlaying ? (
        <div className="grid grid-cols-2 gap-4 w-full">
          <button onClick={() => handleDecision(true)} className="py-3 bg-emerald-900/10 hover:bg-emerald-600 border border-emerald-500/30 text-emerald-400 hover:text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer">
            Match (Same)
          </button>
          <button onClick={() => handleDecision(false)} className="py-3 bg-rose-900/10 hover:bg-rose-600 border border-rose-500/30 text-rose-455 hover:text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer">
            Different
          </button>
        </div>
      ) : (
        <button onClick={startTest} className="w-full py-3.5 bg-gradient-to-r from-teal-500 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">Start 1-Back Run</button>
      )}
    </div>
  );
}

// ============================================================================
// GAME 20: ZEN BREATHING
// ============================================================================
function ZenBreathingGame() {
  const [phase, setPhase] = useState('Inhale'); // Inhale, Hold, Exhale
  const [seconds, setSeconds] = useState(4);
  const [cycles, setCycles] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const timerRef = useRef(null);

  const startZen = () => {
    setIsPlaying(true);
    setPhase('Inhale');
    setSeconds(4);
    setCycles(0);

    if (timerRef.current) clearInterval(timerRef.current);
    timerRef.current = setInterval(() => {
      setSeconds(s => {
        if (s <= 1) {
          setPhase(p => {
            if (p === 'Inhale') {
              playSynthTone(550);
              return 'Hold';
            }
            if (p === 'Hold') {
              playSynthTone(400);
              return 'Exhale';
            }
            // Exhale complete
            playSynthTone(300);
            setCycles(c => c + 1);
            return 'Inhale';
          });
          return 4;
        }
        return s - 1;
      });
    }, 1000);
  };

  const stopZen = () => {
    clearInterval(timerRef.current);
    setIsPlaying(false);
  };

  useEffect(() => { return () => clearInterval(timerRef.current); }, []);

  return (
    <div className="max-w-md mx-auto glass-card p-6 rounded-[2rem] border border-teal-500/10 flex flex-col items-center gap-6">
      <div className="w-full flex justify-between items-center text-xs font-mono font-bold select-none text-slate-355">
        <div>BREATH CYCLES: <span className="text-teal-400 font-black text-sm">{cycles} Complete</span></div>
      </div>
      <div className="flex flex-col items-center justify-center bg-slate-950 p-6 rounded-2xl w-full border border-slate-900 h-52 relative overflow-hidden select-none">
        {isPlaying ? (
          <div className="text-center space-y-4 z-10">
            <span className={`text-4xl font-black uppercase tracking-widest transition-all duration-700 ${
              phase === 'Inhale' ? 'text-emerald-400 scale-110 animate-pulse' :
              phase === 'Hold' ? 'text-amber-400 scale-100' : 'text-sky-400 scale-90'
            }`}>
              {phase}
            </span>
            <div className="text-xl font-black text-slate-100 font-mono">{seconds}s</div>
          </div>
        ) : (
          <span className="text-slate-500 font-bold text-xs uppercase tracking-wider text-center">Guided box breathing rhythm</span>
        )}

        {/* Breathing expanding circle visualizer */}
        {isPlaying && (
          <div
            className={`absolute rounded-full border-4 border-teal-500/10 bg-teal-500/5 transition-all duration-1000 ${
              phase === 'Inhale' ? 'w-44 h-44 opacity-80' :
              phase === 'Hold' ? 'w-48 h-48 opacity-100 border-teal-500/20' : 'w-24 h-24 opacity-30'
            }`}
          />
        )}
      </div>
      {isPlaying ? (
        <button onClick={stopZen} className="w-full py-3.5 bg-slate-900 hover:bg-slate-850 text-slate-350 border border-slate-800 font-bold text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer">
          Stop breathing guide
        </button>
      ) : (
        <button onClick={startZen} className="w-full py-3.5 bg-gradient-to-r from-teal-555 to-teal-650 text-white font-black text-xs uppercase tracking-widest rounded-xl transition-all cursor-pointer shadow-md">
          Start Breathing Guide
        </button>
      )}
    </div>
  );
}
